resilience4j:
  circuitbreaker:
    instances:
      ProfileMs:
        registerHealthIndicator: true
        slidingWindowSize:5
        failureRateThreshold:50
        waitDurationInOpenState:10s
        permittedNumberOfCallsInHalfOpenState:3
        minimumNumberOfCalls:5

feign:
  circuitbreaker:
    enabled:true